import type { AnswerValue, SurveyConfig, SurveyQuestion } from '@/types/database';
export const defaultConfig: SurveyConfig = { title:'お客様アンケート',questionFontSize:17,description:'サービス向上のため、ご意見をお聞かせください。',introText:'お忙しいところ恐れ入りますが、アンケートにご協力ください。',anonymousText:'このアンケートは匿名です。個人を特定する情報は取得しません。',completionText:'ご回答ありがとうございました。いただいたご意見は、今後より良いサービスづくりに活用させていただきます。',submitLabel:'回答を送信',buttonLabel:'回答を送信',primaryColor:'#5E969E',secondaryColor:'#DDEDEF',accentColor:'#397780',backgroundColor:'#F5F9F9',heroOverlayColor:'#397780',heroTextColor:'#FFFFFF',buttonBackground:'#5E969E',buttonTextColor:'#FFFFFF',cardBackground:'#FFFFFF',logoBadgeBackground:'#DDEDEF',themeId:'clinic-clean',heroBackgroundType:'soft-gradient',heroLabel:'QUESTIONNAIRE',heroTitle:'お客様アンケート',heroSubtitle:'サービス向上のため、ご意見をお聞かせください。',logoMode:'icon',cardRadius:18,logoUrl:null,iconUrl:null,googleReviewUrl:null,googleReviewMode:'disabled',completionRules:[] };
export function normalizeQuestionFontSize(value:unknown){const number=Number(value);return Number.isFinite(number)?Math.min(22,Math.max(14,Math.round(number))):17;}
export function scoreMax(q:SurveyQuestion):5|10{return q.settings.maxScore===5?5:10;}
export function choicePresentation(q:SurveyQuestion):'radio'|'select'{return q.settings.presentation==='select'?'select':'radio';}
export function googleReviewMode(config:SurveyConfig):'disabled'|'all'{if(!config.googleReviewUrl)return 'disabled';return config.googleReviewMode==='disabled'?'disabled':'all';}
export function slugify(value:string){ return value.normalize('NFKC').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60); }
export function validateSlug(value:string){ return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value) && value.length <= 60; }
export function validateQuestion(q:SurveyQuestion){ if(!q.title.trim()) return '質問文を入力してください。'; if((q.type==='single_choice'||q.type==='multiple_choice')&&q.options.filter(o=>o.label.trim()).length<2) return '選択式には2件以上の選択肢が必要です。'; return null; }
export function validateAnswers(questions:SurveyQuestion[], answers:Record<string,AnswerValue>){ const errors:Record<string,string>={}; for(const q of questions){ const v=answers[q.id]; const empty=v===undefined||v===null||v===''||(Array.isArray(v)&&v.length===0); if(q.required&&empty){errors[q.id]='この項目は必須です';continue;}if(empty)continue;if(q.type==='rating_10'&&(!Number.isInteger(Number(v))||Number(v)<1||Number(v)>scoreMax(q)))errors[q.id]=`1〜${scoreMax(q)}の評価を選択してください`;if(q.type==='single_choice'&&!q.options.some(o=>o.value===v))errors[q.id]='選択肢から回答してください';if(q.type==='multiple_choice'&&(!Array.isArray(v)||v.some(value=>!q.options.some(o=>o.value===value))))errors[q.id]='選択肢から回答してください'; } return errors; }
export function calculateScores(questions:SurveyQuestion[],answers:Record<string,AnswerValue>){ const scores=questions.filter(q=>q.type==='rating_10').map(q=>({value:Number(answers[q.id]),max:scoreMax(q)})).filter(x=>Number.isFinite(x.value)&&x.value>=1&&x.value<=x.max).map(x=>x.value); const total=scores.reduce((a,b)=>a+b,0); return {totalScore:total,averageScore:scores.length?Number((total/scores.length).toFixed(2)):null}; }
export function csvEscape(value:unknown){ const text=Array.isArray(value)?value.join(' / '):String(value??''); return `"${text.replace(/"/g,'""')}"`; }
