'use client';
import {useActionState,useMemo,useState} from 'react';
import {saveCompletionSettingsAction} from '@/app/actions';
import {googleReviewMode,scoreMax} from '@/lib/survey';
import type {CompletionRule,GoogleReviewMode,GoogleReviewRule,RuleCondition,SurveyConfig,SurveyQuestion} from '@/types/database';
const MAX_RULES=20,MAX_CONDITIONS=10;

export function CompletionSettingsForm({surveyId,versionId,config,questions}:{surveyId:string;versionId:string;config:SurveyConfig;questions:SurveyQuestion[]}){
  const [state,action,pending]=useActionState(saveCompletionSettingsAction.bind(null,surveyId,versionId),null),scores=questions.filter(q=>q.type==='rating_10');
  const initialReviewRule=useMemo<GoogleReviewRule>(()=>{
    if(config.googleReviewRule?.conditions.length)return config.googleReviewRule;
    const completionRule=config.completionRules?.find(rule=>rule.conditions.length);
    if(completionRule)return {logic:completionRule.logic,conditions:completionRule.conditions.map(condition=>({...condition}))};
    return {logic:'and',conditions:scores[0]?[{questionId:scores[0].id,operator:'gte',value:scoreMax(scores[0])}]:[]};
  },[config.googleReviewRule,config.completionRules,scores]);
  const [mode,setMode]=useState<GoogleReviewMode>(googleReviewMode(config)),[reviewRule,setReviewRule]=useState<GoogleReviewRule>(initialReviewRule),[rules,setRules]=useState<CompletionRule[]>(config.completionRules??[]);
  const clamp=(condition:RuleCondition)=>{const question=scores.find(q=>q.id===condition.questionId),max=question?scoreMax(question):10;return {...condition,value:Math.min(Math.max(1,condition.value||1),max)}};
  const patchReviewCondition=(ci:number,value:Partial<RuleCondition>)=>setReviewRule(rule=>({...rule,conditions:rule.conditions.map((condition,index)=>index===ci?clamp({...condition,...value}):condition)}));
  const addReviewCondition=()=>scores[0]&&setReviewRule(rule=>({...rule,conditions:[...rule.conditions,{questionId:scores[0].id,operator:'gte',value:scoreMax(scores[0])}]}));
  const patchRule=(i:number,value:Partial<CompletionRule>)=>setRules(xs=>xs.map((x,n)=>n===i?{...x,...value}:x));
  const patchCondition=(ri:number,ci:number,value:Partial<RuleCondition>)=>setRules(xs=>xs.map((r,n)=>n!==ri?r:{...r,conditions:r.conditions.map((c,m)=>m===ci?clamp({...c,...value}):c)}));
  const addRule=()=>setRules(xs=>[...xs,{id:crypto.randomUUID(),logic:'and',conditions:[{questionId:scores[0]?.id??'',operator:'gte',value:scores[0]?scoreMax(scores[0]):1}],completionMessage:'',needsFollowUp:false}]);
  return <form action={action} className="card stack admin-form-card"><div><p className="form-kicker">回答後</p><h2>口コミ・完了条件</h2><p className="muted">Google口コミ導線の表示条件と、条件別の回答後処理を設定します。</p></div>
    <fieldset className="review-mode-grid"><legend>Google口コミ導線モード</legend>{([['disabled','使用しない','通常のサンクス画面のみ表示'],['all','全回答者に表示','回答完了者全員へ案内'],['score','スコア条件で表示','指定した評価質問の条件を満たした回答だけに案内']] as const).map(([value,label,help])=><label className={mode===value?'selected':''} key={value}><input type="radio" name="googleReviewMode" value={value} checked={mode===value} onChange={()=>setMode(value)}/><span><strong>{label}</strong><small>{help}</small></span></label>)}</fieldset>
    {mode!=='disabled'&&<label className="field" id="googleReview">Google口コミURL<input name="googleReviewUrl" type="url" required defaultValue={config.googleReviewUrl??''} placeholder="https://g.page/r/..."/></label>}
    {mode==='score'&&<section className="completion-rule stack"><div><h3>口コミを表示するスコア条件</h3><p className="muted">ここで設定した条件を回答送信時にサーバーで判定し、成立した場合だけGoogle口コミCTAを表示します。合計点ではなく各質問を個別に評価します。</p></div><label className="field">条件のつなぎ方<select value={reviewRule.logic} onChange={e=>setReviewRule(rule=>({...rule,logic:e.target.value as 'and'|'or'}))}><option value="and">AND（すべて一致）</option><option value="or">OR（いずれか一致）</option></select></label>
      {reviewRule.conditions.map((condition,ci)=>{const question=scores.find(q=>q.id===condition.questionId),max=question?scoreMax(question):10;return <div className="condition-row" key={`review-${ci}`}><strong>条件 {ci+1}</strong><label className="field">対象質問<select value={condition.questionId} onChange={e=>patchReviewCondition(ci,{questionId:e.target.value})}>{scores.map((q,index)=><option key={q.id} value={q.id}>Q{index+1} {q.title}</option>)}</select></label><label className="field">比較<select value={condition.operator} onChange={e=>patchReviewCondition(ci,{operator:e.target.value as RuleCondition['operator']})}><option value="gte">以上</option><option value="lte">以下</option><option value="eq">等しい</option></select></label><label className="field">条件値<input type="number" min="1" max={max} value={Math.min(condition.value,max)} onChange={e=>patchReviewCondition(ci,{value:Number(e.target.value)})}/></label><button className="btn danger" type="button" disabled={reviewRule.conditions.length<=1} onClick={()=>setReviewRule(rule=>({...rule,conditions:rule.conditions.filter((_,index)=>index!==ci)}))}>削除</button></div>})}
      <button className="btn secondary" type="button" disabled={!scores.length||reviewRule.conditions.length>=MAX_CONDITIONS} onClick={addReviewCondition}>＋ 口コミ表示条件を追加</button>{!scores.length&&<small className="muted">スコア条件を使うにはrating（評価）質問を追加してください。</small>}<input type="hidden" name="googleReviewRule" value={JSON.stringify(reviewRule)}/></section>}
    <div className="stack conditional-settings"><div><h3>条件別の回答後処理</h3><p className="muted">サンクスメッセージや要フォロー判定を変更するための条件です。口コミ表示条件は上の「口コミを表示するスコア条件」で設定してください。</p></div>
      {rules.map((rule,ri)=><section className="completion-rule" key={rule.id}><label className="field">条件のつなぎ方<select value={rule.logic} onChange={e=>patchRule(ri,{logic:e.target.value as 'and'|'or'})}><option value="and">AND（すべて一致）</option><option value="or">OR（いずれか一致）</option></select></label>
        {rule.conditions.map((condition,ci)=>{const question=scores.find(q=>q.id===condition.questionId),max=question?scoreMax(question):10;return <div className="condition-row" key={`${rule.id}-${ci}`}><strong>条件 {ci+1}</strong><label className="field">対象質問<select value={condition.questionId} onChange={e=>patchCondition(ri,ci,{questionId:e.target.value})}>{scores.map((q,index)=><option key={q.id} value={q.id}>Q{index+1} {q.title}</option>)}</select></label><label className="field">比較<select value={condition.operator} onChange={e=>patchCondition(ri,ci,{operator:e.target.value as RuleCondition['operator']})}><option value="gte">以上</option><option value="lte">以下</option><option value="eq">等しい</option></select></label><label className="field">条件値<input type="number" min="1" max={max} value={Math.min(condition.value,max)} onChange={e=>patchCondition(ri,ci,{value:Number(e.target.value)})}/></label><button className="btn danger" type="button" disabled={rule.conditions.length<=1} onClick={()=>patchRule(ri,{conditions:rule.conditions.filter((_,n)=>n!==ci)})}>削除</button></div>})}
        <label className="field">条件一致時のサンクスメッセージ<textarea rows={3} value={rule.completionMessage??''} onChange={e=>patchRule(ri,{completionMessage:e.target.value})}/></label><label><input type="checkbox" checked={Boolean(rule.needsFollowUp)} onChange={e=>patchRule(ri,{needsFollowUp:e.target.checked})}/> 管理画面で要フォローとして扱う</label>
        <div className="row"><button className="btn secondary" type="button" disabled={rule.conditions.length>=MAX_CONDITIONS||!scores.length} onClick={()=>patchRule(ri,{conditions:[...rule.conditions,{questionId:scores[0]?.id??'',operator:'gte',value:scores[0]?scoreMax(scores[0]):1}]})}>＋ 条件を追加</button><button className="btn danger" type="button" onClick={()=>setRules(xs=>xs.filter((_,n)=>n!==ri))}>ルールを削除</button></div></section>)}
      <button className="btn secondary" type="button" disabled={!scores.length||rules.length>=MAX_RULES} onClick={addRule}>＋ 完了条件ルールを追加</button>{!scores.length&&<small className="muted">rating（評価）質問を追加すると条件を設定できます。</small>}</div>
    <input type="hidden" name="completionRules" value={JSON.stringify(rules)}/>{state?.error&&<p className="error" role="alert">{state.error}</p>}{state?.success&&<p className="notice" role="status">{state.success}</p>}<button className="btn" disabled={pending}>{pending?'保存中…':'口コミ・完了条件を保存'}</button>
  </form>;
}
