'use client';
import {useActionState,useState} from 'react';
import {saveCompletionSettingsAction} from '@/app/actions';
import {googleReviewMode,scoreMax} from '@/lib/survey';
import type {CompletionRule,GoogleReviewMode,RuleCondition,SurveyConfig,SurveyQuestion} from '@/types/database';
const MAX_RULES=20,MAX_CONDITIONS=10;

export function CompletionSettingsForm({surveyId,versionId,config,questions}:{surveyId:string;versionId:string;config:SurveyConfig;questions:SurveyQuestion[]}){
  const [state,action,pending]=useActionState(saveCompletionSettingsAction.bind(null,surveyId,versionId),null),scores=questions.filter(q=>q.type==='rating_10');
  const [mode,setMode]=useState<GoogleReviewMode>(googleReviewMode(config)),[rules,setRules]=useState<CompletionRule[]>(config.completionRules??[]);
  const patchRule=(i:number,value:Partial<CompletionRule>)=>setRules(xs=>xs.map((x,n)=>n===i?{...x,...value}:x));
  const patchCondition=(ri:number,ci:number,value:Partial<RuleCondition>)=>setRules(xs=>xs.map((r,n)=>n!==ri?r:{...r,conditions:r.conditions.map((c,m)=>{if(m!==ci)return c;const next={...c,...value},question=scores.find(q=>q.id===next.questionId);return {...next,value:Math.min(Math.max(1,next.value||1),question?scoreMax(question):10)}})}));
  const addRule=()=>setRules(xs=>[...xs,{id:crypto.randomUUID(),logic:'and',conditions:[{questionId:scores[0]?.id??'',operator:'gte',value:scores[0]?scoreMax(scores[0]):1}],completionMessage:'',needsFollowUp:false}]);
  return <form action={action} className="card stack admin-form-card"><div><p className="form-kicker">回答後</p><h2>口コミ・完了条件</h2><p className="muted">Google口コミ導線と、条件別の回答後処理をそれぞれ設定します。</p></div>
    <fieldset className="review-mode-grid"><legend>Google口コミ導線モード</legend>{([['disabled','使用しない','通常のサンクス画面のみ表示'],['all','全回答者に表示','回答内容や点数に関係なく全員へ案内']] as const).map(([value,label,help])=><label className={mode===value?'selected':''} key={value}><input type="radio" name="googleReviewMode" value={value} checked={mode===value} onChange={()=>setMode(value)}/><span><strong>{label}</strong><small>{help}</small></span></label>)}</fieldset>
    <p className="muted">有効時は得点・回答内容に関係なく、すべての回答者へ同じCTAを表示します。</p>
    {mode==='all'&&<label className="field" id="googleReview">Google口コミURL<input name="googleReviewUrl" type="url" required defaultValue={config.googleReviewUrl??''} placeholder="https://g.page/r/..."/></label>}
    <div className="stack conditional-settings"><div><h3>条件別の回答後処理</h3><p className="muted">条件に応じてサンクスメッセージと要フォロー判定を変更します。Google口コミ導線の表示可否には影響しません。</p></div>
      {rules.map((rule,ri)=><section className="completion-rule" key={rule.id}><label className="field">条件のつなぎ方<select value={rule.logic} onChange={e=>patchRule(ri,{logic:e.target.value as 'and'|'or'})}><option value="and">AND（すべて一致）</option><option value="or">OR（いずれか一致）</option></select></label>
        {rule.conditions.map((condition,ci)=>{const question=scores.find(q=>q.id===condition.questionId),max=question?scoreMax(question):10;return <div className="condition-row" key={`${rule.id}-${ci}`}><strong>条件 {ci+1}</strong><label className="field">対象質問<select value={condition.questionId} onChange={e=>patchCondition(ri,ci,{questionId:e.target.value})}>{scores.map((q,index)=><option key={q.id} value={q.id}>Q{index+1} {q.title}</option>)}</select></label><label className="field">比較<select value={condition.operator} onChange={e=>patchCondition(ri,ci,{operator:e.target.value as RuleCondition['operator']})}><option value="gte">以上</option><option value="lte">以下</option><option value="eq">等しい</option></select></label><label className="field">条件値<input type="number" min="1" max={max} value={Math.min(condition.value,max)} onChange={e=>patchCondition(ri,ci,{value:Number(e.target.value)})}/></label><button className="btn danger" type="button" disabled={rule.conditions.length<=1} onClick={()=>patchRule(ri,{conditions:rule.conditions.filter((_,n)=>n!==ci)})}>削除</button></div>})}
        <label className="field">条件一致時のサンクスメッセージ<textarea rows={3} value={rule.completionMessage??''} onChange={e=>patchRule(ri,{completionMessage:e.target.value})}/></label><label><input type="checkbox" checked={Boolean(rule.needsFollowUp)} onChange={e=>patchRule(ri,{needsFollowUp:e.target.checked})}/> 管理画面で要フォローとして扱う</label>
        <div className="row"><button className="btn secondary" type="button" disabled={rule.conditions.length>=MAX_CONDITIONS||!scores.length} onClick={()=>patchRule(ri,{conditions:[...rule.conditions,{questionId:scores[0]?.id??'',operator:'gte',value:scores[0]?scoreMax(scores[0]):1}]})}>＋ 条件を追加</button><button className="btn danger" type="button" onClick={()=>setRules(xs=>xs.filter((_,n)=>n!==ri))}>ルールを削除</button></div></section>)}
      <button className="btn secondary" type="button" disabled={!scores.length||rules.length>=MAX_RULES} onClick={addRule}>＋ 完了条件ルールを追加</button>{!scores.length&&<small className="muted">rating（評価）質問を追加すると条件を設定できます。</small>}</div>
    <input type="hidden" name="completionRules" value={JSON.stringify(rules)}/>{state?.error&&<p className="error" role="alert">{state.error}</p>}{state?.success&&<p className="notice" role="status">{state.success}</p>}<button className="btn" disabled={pending}>{pending?'保存中…':'口コミ・完了条件を保存'}</button>
  </form>;
}
