'use client';
import type {SurveyConfig} from '@/types/database';
import {AssetUrlField} from './AssetUrlField';
export function DesignFields({config,onChange,surveyId}:{config:SurveyConfig;onChange:(patch:Partial<SurveyConfig>)=>void;surveyId:string}) {
  return <div className="stack"><label className="field">業種名・サブタイトル<input value={config.subtitle??''} onChange={e=>onChange({subtitle:e.target.value})}/></label><label className="field">ロゴ<select value={config.logoMode??'none'} onChange={e=>onChange({logoMode:e.target.value as SurveyConfig['logoMode']})}><option value="none">ロゴなし</option><option value="icon">アイコン表示</option><option value="upload">ロゴ画像アップロード</option></select></label>{config.logoMode==='upload'&&<AssetUrlField name="logoUrl" label="ロゴ画像" initial={config.logoUrl??''} surveyId={surveyId} onChange={value=>onChange({logoUrl:value})}/>}
    <div className="theme-color-grid">{([['primaryColor','メインカラー'],['backgroundColor','背景色'],['cardBackground','カード背景'],['buttonBackground','ボタン背景'],['buttonTextColor','ボタン文字']] as const).map(([key,label])=><label className="field" key={key}>{label}<input type="color" value={config[key]??'#ffffff'} onChange={e=>onChange({[key]:e.target.value,...(key==='primaryColor'?{heroOverlayColor:e.target.value,buttonBackground:e.target.value}:{})})}/></label>)}</div>
    {([['heroTitle','メインタイトル'],['description','説明文'],['anonymousText','匿名案内文'],['completionText','サンクス画面の文章'],['submitLabel','ボタン文言']] as const).map(([key,label])=><label className="field" key={key}>{label}<textarea value={config[key]??''} onChange={e=>onChange({[key]:e.target.value,...(key==='heroTitle'?{title:e.target.value}:key==='submitLabel'?{buttonLabel:e.target.value}:{})})}/></label>)}
    <fieldset className="stack"><legend>文字サイズ</legend>{([['business','店舗・医院名',16,18,22],['title','メインタイトル',22,26,30],['description','説明文',13,15,17],['choice','選択肢',16,17,19],['button','ボタン',16,17,19]] as const).map(([key,label,small,normal,large])=><label className="field" key={key}>{label}<select value={config.fontSizes?.[key]??normal} onChange={e=>onChange({fontSizes:{...config.fontSizes,[key]:Number(e.target.value)}})}><option value={small}>小さい</option><option value={normal}>標準</option><option value={large}>大きい</option></select></label>)}<label className="field">質問文<select value={config.questionFontSize??17} onChange={e=>onChange({questionFontSize:Number(e.target.value)})}><option value="15">小さい</option><option value="17">標準</option><option value="20">大きい</option></select></label></fieldset>
  </div>;
}
