'use client';
import {useEffect,useState} from 'react';
import {SurveyRenderer} from '@/components/survey/SurveyRenderer';
import {googleReviewMode} from '@/lib/survey';
import type {SurveyVersion} from '@/types/database';
type View='survey'|'thanks'|'review';
export function LiveSurveyPreview({name,version,onEdit,className=''}:{name:string;version:SurveyVersion;onEdit?:(target:string)=>void;className?:string}){
  const [view,setView]=useState<View>('survey'),[open,setOpen]=useState(false);
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>event.key==='Escape'&&setOpen(false);document.body.classList.add('preview-modal-open');document.addEventListener('keydown',close);return()=>{document.body.classList.remove('preview-modal-open');document.removeEventListener('keydown',close)}},[open]);
  const config=version.config,panel=<div className="live-preview-shell"><div className="preview-toolbar" role="tablist" aria-label="プレビュー表示"><button type="button" className={view==='survey'?'active':''} onClick={()=>setView('survey')}>本編</button><button type="button" className={view==='thanks'?'active':''} onClick={()=>setView('thanks')}>サンクス</button><button type="button" className={view==='review'?'active':''} onClick={()=>setView('review')}>口コミ導線</button></div><div className="admin-phone-frame">{view==='survey'?<SurveyRenderer name={name} slug="preview" version={version} preview onEditTarget={onEdit}/>:<CompletionPreview showReview={view==='review'&&googleReviewMode(config)==='all'&&Boolean(config.googleReviewUrl)} reviewView={view==='review'} text={config.completionText} color={config.primaryColor} onEdit={onEdit}/>}</div><p className="preview-hint">プレビュー内をクリックすると、左側の編集項目へ移動します。</p></div>;
  return <><aside className={`live-preview-column ${className}`} aria-label="ライブプレビュー"><div className="preview-column-heading"><div><span>LIVE PREVIEW</span><strong>スマホでの見え方</strong></div><span className="live-badge">● リアルタイム</span></div>{panel}</aside><button className="mobile-preview-trigger" type="button" onClick={()=>setOpen(true)}>👁 プレビューを見る</button>{open&&<div className="mobile-preview-overlay" role="dialog" aria-modal="true" aria-label="ライブプレビュー"><button className="mobile-preview-close" type="button" onClick={()=>setOpen(false)}>× 閉じる</button>{panel}</div>}</>;
}
function CompletionPreview({showReview,reviewView,text,color,onEdit}:{showReview:boolean;reviewView:boolean;text:string;color:string;onEdit?:(target:string)=>void}){return <div className="completion-preview" style={{'--preview-brand':color} as React.CSSProperties}><div className="completion-check">✓</div><p className="eyebrow">THANK YOU</p><button type="button" className="preview-editable completion-copy" onClick={()=>onEdit?.('completionText')}><strong>ご回答ありがとうございました</strong><span>{text}</span></button>{showReview?<div className="review-preview"><span>Google</span><h3>口コミにもご協力ください</h3><p>あなたの声が、これから利用する方の参考になります。</p><button type="button" onClick={()=>onEdit?.('googleReview')}>Google口コミを書く</button><small className="muted">回答内容や点数にかかわらず、全回答者に表示されます。</small></div>:<p className="completion-normal">{reviewView?'口コミ導線を「全回答者に表示」にしてURLを設定すると、ここで確認できます。':'送信が完了しました。画面を閉じてください。'}</p>}</div>}
