import Link from 'next/link';
import {SurveyActionsMenu} from '@/components/admin/SurveyActionsMenu';
import {PublicUrlActions} from '@/components/admin/PublicUrlActions';
import type {Role} from '@/types/database';
type Owner={name?:string|null;email?:string|null};
type SurveyRow={id:string;name:string;slug:string;industry:string;status:string;updated_at:string;responses?:Array<{count:number}>;owner?:Owner|Owner[]|null};
type SessionRow={id:string;context?:{storeName?:string;businessType?:string};updated_at:string};
export const statusLabel:Record<string,string>={draft:'下書き',published:'公開中',unpublished:'非公開',archived:'削除済み'};
export function SurveyListTable({surveys,sessions,role,baseUrl}:{surveys:SurveyRow[];sessions:SessionRow[];role:Role;baseUrl:string}){return <section className="crm-list-card" id="survey-list"><table className="crm-table compact-table"><thead><tr><th>店舗・医院</th><th>ステータス</th><th>回答数</th><th>公開URL</th><th>最終更新</th><th>操作</th></tr></thead><tbody>{sessions.map(session=><tr key={session.id} className="in-progress-row"><td data-label="店舗・医院"><strong>{session.context?.storeName||'名称未入力'}</strong><small className="survey-meta">{session.context?.businessType||'業種未設定'} ・ 設計ヒアリング中</small></td><td data-label="ステータス"><span className="status-badge in_progress">作成途中</span></td><td data-label="回答数">—</td><td data-label="公開URL">—</td><td data-label="最終更新">{new Date(session.updated_at).toLocaleDateString('ja-JP')}</td><td data-label="操作"><Link className="table-primary-action" href={`/admin/surveys/new?session=${session.id}`}>続きから作成</Link></td></tr>)}{surveys.map(survey=>{const owner=Array.isArray(survey.owner)?survey.owner[0]:survey.owner,ownerName=owner?.name||owner?.email||'未設定',responseCount=survey.responses?.[0]?.count??0;return <tr key={survey.id}><td data-label="店舗・医院"><Link className="survey-name-link" href={`/admin/surveys/${survey.id}`}>{survey.name}</Link><small className="survey-meta">{survey.industry||'業種未設定'} ・ 担当 {ownerName}</small></td><td data-label="ステータス"><span className={`status-badge ${survey.status}`}>{statusLabel[survey.status]||survey.status}</span></td><td data-label="回答数"><Link href={`/admin/surveys/${survey.id}/responses`} className={`response-count compact-response-count${responseCount===0?' zero':''}`}>{responseCount}件</Link></td><td data-label="公開URL">{survey.status==='published'?<PublicUrlActions url={`${baseUrl}/${survey.slug}`} slug={survey.slug} compact/>:<span className="muted">未公開</span>}</td><td data-label="最終更新">{new Date(survey.updated_at).toLocaleDateString('ja-JP')}</td><td data-label="操作"><SurveyActionsMenu surveyId={survey.id} status={survey.status} role={role}/></td></tr>})}</tbody></table>{surveys.length===0&&sessions.length===0?<div className="empty-state"><span>▤</span><h3>条件に合うアンケートがありません</h3><p>絞り込みを変更するか、新しいアンケートを作成してください。</p><Link className="btn" href="/admin/surveys/new">新しいアンケートを作成</Link></div>:null}</section>}
