import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {getUser} from '@/lib/data';
import {StatusCard} from '@/components/admin/StatusCard';
import {SurveyListTable} from '@/components/admin/SurveyListTable';
import {appUrl} from '@/lib/env';

export default async function AdminPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;industry?:string}>}){
  const query=await searchParams,supabase=await createClient(),user=await getUser();
  const [surveyResult,sessionResult]=await Promise.all([supabase.from('surveys').select('id,name,slug,industry,status,updated_at,published_at,responses(count),owner:profiles!surveys_owner_user_id_fkey(name,email)').neq('status','archived').order('updated_at',{ascending:false}),supabase.from('builder_sessions').select('id,context,current_step,updated_at').eq('status','in_progress').order('updated_at',{ascending:false})]);
  const allSurveys=surveyResult.data??[],allSessions=sessionResult.data??[],keyword=(query.q??'').trim().toLowerCase(),filter=query.status??'all';
  const surveys=allSurveys.filter(item=>(!keyword||item.name.toLowerCase().includes(keyword)||item.slug.toLowerCase().includes(keyword))&&(!query.industry||item.industry===query.industry)&&(filter==='all'||filter==='responses'?(filter==='all'||(item.responses?.[0]?.count??0)>0):item.status===filter));
  const sessions=(filter==='all'||filter==='in_progress'?allSessions:[]).filter(item=>!keyword||String(item.context?.storeName??'').toLowerCase().includes(keyword));
  const responseTotal=allSurveys.reduce((sum,item)=>sum+(item.responses?.[0]?.count??0),0),industries=[...new Set(allSurveys.map(item=>item.industry).filter(Boolean))];
  return <div className="crm-dashboard"><header className="dashboard-heading"><div><p>ダッシュボード</p><h1>アンケート管理</h1><span>店舗ごとの作成状況と回答を、ここでまとめて確認できます。</span></div><Link className="btn dashboard-create" href="/admin/surveys/new">＋ 新しいアンケート</Link></header><section className="status-grid" aria-label="ステータス概要"><StatusCard label="作成途中" count={allSessions.length} description="ヒアリングの続きがあります" href="/admin?status=in_progress" tone="amber"/><StatusCard label="下書き" count={allSurveys.filter(item=>item.status==='draft'||item.status==='unpublished').length} description="公開前の確認が必要です" href="/admin?status=draft" tone="slate"/><StatusCard label="公開中" count={allSurveys.filter(item=>item.status==='published').length} description="お客様が回答できます" href="/admin?status=published" tone="green"/><StatusCard label="回答数" count={responseTotal} description="すべてのアンケート合計" href="/admin?status=responses" tone="blue"/></section><section className="list-heading"><div><h2>アンケート一覧</h2><p>{surveys.length+sessions.length}件を表示しています</p></div><form className="crm-filters" method="get"><label><span className="sr-only">キーワード検索</span><input name="q" defaultValue={query.q} placeholder="店舗名・医院名で検索"/></label><label><span className="sr-only">ステータス</span><select name="status" defaultValue={filter}><option value="all">すべての状態</option><option value="in_progress">作成途中</option><option value="draft">下書き</option><option value="published">公開中</option><option value="unpublished">非公開</option><option value="responses">回答あり</option></select></label><label><span className="sr-only">業種</span><select name="industry" defaultValue={query.industry??''}><option value="">すべての業種</option>{industries.map(industry=><option value={industry} key={industry}>{industry}</option>)}</select></label><button className="filter-submit" type="submit">絞り込む</button>{(keyword||filter!=='all'||query.industry)&&<Link href="/admin" className="filter-reset">解除</Link>}</form></section><SurveyListTable surveys={surveys} sessions={sessions} role={user?.role??'sales'} baseUrl={appUrl()}/></div>;
}
