import type { BuilderBusinessType, SurveyConfig, SurveyThemeId } from '@/types/database';

export interface SurveyThemeTemplate {
  id:SurveyThemeId; label:string; description:string;
  config:Required<Pick<SurveyConfig,'primaryColor'|'secondaryColor'|'accentColor'|'backgroundColor'|'heroOverlayColor'|'heroTextColor'|'buttonBackground'|'buttonTextColor'|'cardBackground'|'logoBadgeBackground'|'heroBackgroundType'|'heroTitle'|'heroSubtitle'|'logoMode'|'cardRadius'|'submitLabel'|'introText'|'completionText'>>;
}

export const surveyThemeTemplates:Record<SurveyThemeId,SurveyThemeTemplate>={
  'clinic-clean':{id:'clinic-clean',label:'Clinic Clean',description:'清潔感と安心感を重視した医療向け',config:{primaryColor:'#5E969E',secondaryColor:'#DDEDEF',accentColor:'#397780',backgroundColor:'#F5F9F9',heroOverlayColor:'#397780',heroTextColor:'#FFFFFF',buttonBackground:'#5E969E',buttonTextColor:'#FFFFFF',cardBackground:'#FFFFFF',logoBadgeBackground:'#DDEDEF',heroBackgroundType:'soft-gradient',heroTitle:'患者様アンケート',heroSubtitle:'より良い診療とサービスのために、ご意見をお聞かせください。',logoMode:'icon',cardRadius:18,submitLabel:'回答を送信',introText:'こちらのアンケートは匿名です。今後の診療・サービス改善のため、率直なご意見をお聞かせください。',completionText:'ご回答ありがとうございました。いただいたご意見は、より良い診療環境づくりに活用いたします。'}},
  'restaurant-clean':{id:'restaurant-clean',label:'Restaurant Clean',description:'温かさと清潔感のある飲食店向け',config:{primaryColor:'#8B5535',secondaryColor:'#F2E4D8',accentColor:'#B98558',backgroundColor:'#FCF8F3',heroOverlayColor:'#704128',heroTextColor:'#FFFDF9',buttonBackground:'#8B5535',buttonTextColor:'#FFFFFF',cardBackground:'#FFFDF9',logoBadgeBackground:'#F2E4D8',heroBackgroundType:'soft-gradient',heroTitle:'お客様アンケート',heroSubtitle:'また来たいと思えるお店づくりのため、ご感想をお聞かせください。',logoMode:'icon',cardRadius:20,submitLabel:'回答を送信',introText:'今後のサービス改善のため、お料理や接客について率直なご意見をお聞かせください。',completionText:'ご回答ありがとうございました。いただいたご意見は、より良いお店づくりに活用いたします。'}},
  'salon-clean':{id:'salon-clean',label:'Salon Clean',description:'上品でやわらかな美容室・サロン向け',config:{primaryColor:'#9A758C',secondaryColor:'#EEE3EA',accentColor:'#765568',backgroundColor:'#FBF8FA',heroOverlayColor:'#765568',heroTextColor:'#FFFFFF',buttonBackground:'#9A758C',buttonTextColor:'#FFFFFF',cardBackground:'#FFFFFF',logoBadgeBackground:'#EEE3EA',heroBackgroundType:'soft-gradient',heroTitle:'ご来店アンケート',heroSubtitle:'心地よい時間と仕上がりのために、ご感想をお聞かせください。',logoMode:'icon',cardRadius:20,submitLabel:'回答を送信',introText:'今後の技術・サービス改善のため、仕上がりや接客についてご意見をお聞かせください。',completionText:'ご回答ありがとうございました。いただいたご意見を、より良いサロンづくりに活用いたします。'}},
};

export function themeIdForBusiness(type:BuilderBusinessType):SurveyThemeId{return type==='restaurant'?'restaurant-clean':type==='salon'?'salon-clean':'clinic-clean';}
export function getThemeTemplate(id?:SurveyThemeId){return surveyThemeTemplates[id??'clinic-clean'];}
export function resolveSurveyTheme(config:SurveyConfig){const template=getThemeTemplate(config.themeId);return {...template.config,...config,themeId:config.themeId??template.id,secondaryColor:config.secondaryColor??template.config.secondaryColor,accentColor:config.accentColor??template.config.accentColor,heroOverlayColor:config.heroOverlayColor??template.config.heroOverlayColor,heroTextColor:config.heroTextColor??template.config.heroTextColor,buttonBackground:config.buttonBackground??config.primaryColor??template.config.buttonBackground,buttonTextColor:config.buttonTextColor??template.config.buttonTextColor,cardBackground:config.cardBackground??template.config.cardBackground,logoBadgeBackground:config.logoBadgeBackground??config.secondaryColor??template.config.logoBadgeBackground,heroTitle:config.heroTitle||config.title||template.config.heroTitle,heroSubtitle:config.heroSubtitle||config.description||template.config.heroSubtitle,buttonLabel:config.buttonLabel||config.submitLabel||template.config.submitLabel};}
