import type { BuilderBusinessType, SurveyConfig, SurveyThemeId } from '@/types/database';

export interface SurveyThemeTemplate {
  id:SurveyThemeId; label:string; description:string;
  config:Required<Pick<SurveyConfig,'primaryColor'|'secondaryColor'|'accentColor'|'backgroundColor'|'heroOverlayColor'|'heroTextColor'|'buttonBackground'|'buttonTextColor'|'cardBackground'|'logoBadgeBackground'|'heroBackgroundType'|'heroTitle'|'heroSubtitle'|'logoMode'|'cardRadius'|'submitLabel'|'introText'|'completionText'>>;
}

export const surveyThemeTemplates:Record<SurveyThemeId,SurveyThemeTemplate>={
  'clinic-clean':{id:'clinic-clean',label:'Clinic Clean',description:'清潔感と安心感を重視した医療向け',config:{primaryColor:'#62A1A7',secondaryColor:'#E5F0F1',accentColor:'#4E8D93',backgroundColor:'#F8F9F8',heroOverlayColor:'#70AEB4',heroTextColor:'#FFFFFF',buttonBackground:'#62A1A7',buttonTextColor:'#FFFFFF',cardBackground:'#FFFFFF',logoBadgeBackground:'#E5F0F1',heroBackgroundType:'soft-gradient',heroTitle:'患者さまアンケート',heroSubtitle:'より良い医療サービスの提供のため、率直なご意見をお聞かせください',logoMode:'icon',cardRadius:14,submitLabel:'アンケートを送信する',introText:'今後の診療・サービス改善のため、率直なご意見をお聞かせください。',completionText:'ご回答ありがとうございました。いただいたご意見は、より良い診療環境づくりに活用いたします。'}},
  'restaurant-clean':{id:'restaurant-clean',label:'Restaurant Clean',description:'温かさと清潔感のある飲食店向け',config:{primaryColor:'#8B5535',secondaryColor:'#F2E4D8',accentColor:'#B98558',backgroundColor:'#FCFAF7',heroOverlayColor:'#8B5535',heroTextColor:'#FFFDF9',buttonBackground:'#8B5535',buttonTextColor:'#FFFFFF',cardBackground:'#FFFFFF',logoBadgeBackground:'#F2E4D8',heroBackgroundType:'soft-gradient',heroTitle:'お客様アンケート',heroSubtitle:'また来たいと思えるお店づくりのため、ご感想をお聞かせください',logoMode:'icon',cardRadius:14,submitLabel:'アンケートを送信する',introText:'今後のサービス改善のため、お料理や接客について率直なご意見をお聞かせください。',completionText:'ご回答ありがとうございました。いただいたご意見は、より良いお店づくりに活用いたします。'}},
  'salon-clean':{id:'salon-clean',label:'Salon Clean',description:'上品でやわらかな美容室・サロン向け',config:{primaryColor:'#9A758C',secondaryColor:'#EEE3EA',accentColor:'#765568',backgroundColor:'#FBF9FA',heroOverlayColor:'#9A758C',heroTextColor:'#FFFFFF',buttonBackground:'#9A758C',buttonTextColor:'#FFFFFF',cardBackground:'#FFFFFF',logoBadgeBackground:'#EEE3EA',heroBackgroundType:'soft-gradient',heroTitle:'ご来店アンケート',heroSubtitle:'心地よい時間と仕上がりのために、ご感想をお聞かせください',logoMode:'icon',cardRadius:14,submitLabel:'アンケートを送信する',introText:'今後の技術・サービス改善のため、仕上がりや接客についてご意見をお聞かせください。',completionText:'ご回答ありがとうございました。いただいたご意見を、より良いサロンづくりに活用いたします。'}},
};

export function themeIdForBusiness(type:BuilderBusinessType):SurveyThemeId{return type==='restaurant'?'restaurant-clean':type==='salon'?'salon-clean':'clinic-clean';}
export function getThemeTemplate(id?:SurveyThemeId){return surveyThemeTemplates[id??'clinic-clean'];}
export function resolveSurveyTheme(config:SurveyConfig){const template=getThemeTemplate(config.themeId);return {...template.config,...config,themeId:config.themeId??template.id,secondaryColor:config.secondaryColor??template.config.secondaryColor,accentColor:config.accentColor??template.config.accentColor,heroOverlayColor:config.heroOverlayColor??template.config.heroOverlayColor,heroTextColor:config.heroTextColor??template.config.heroTextColor,buttonBackground:config.buttonBackground??config.primaryColor??template.config.buttonBackground,buttonTextColor:config.buttonTextColor??template.config.buttonTextColor,cardBackground:config.cardBackground??template.config.cardBackground,logoBadgeBackground:config.logoBadgeBackground??config.secondaryColor??template.config.logoBadgeBackground,heroTitle:config.heroTitle||config.title||template.config.heroTitle,heroSubtitle:config.heroSubtitle||config.description||template.config.heroSubtitle,buttonLabel:config.buttonLabel||config.submitLabel||template.config.submitLabel};}
