'use client';

import { useCallback, useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { completeBuilderAction, saveBuilderSessionAction } from '@/app/actions';
import { LiveSurveyPreview } from '@/components/admin/LiveSurveyPreview';
import {buildBuilderPreviewVersion,reopenBuilderStep,resolveBuilderPreviewTarget} from '@/components/builder/builderPreview';
import { defaultCompletionText, defaultIntroText, ruleBasedBuilderEngine } from '@/lib/builder/engine';
import type { BuilderContext, BuilderStep, QuestionType, SurveyQuestion } from '@/types/database';

type HistoryEntry={step:BuilderStep;value:unknown;label:string};
type SaveStatus='idle'|'saving'|'saved'|'error';
const labels:Record<string,string>={satisfaction:'顧客満足度',improvement:'店舗改善',patient:'患者アンケート',google_review:'Google口コミ導線',other:'その他',clinic:'クリニック',restaurant:'飲食店',salon:'美容室',decided:'ほぼ決まっている',partial:'一部だけ決まっている',none:'何も決まっていない',clinic_standard:'クリニック標準',restaurant_standard:'飲食店標準',salon_standard:'美容室標準',custom:'自分で作る'};

export function BuilderWorkspace({initial={},initialSessionId=null}:{initial?:BuilderContext;initialSessionId?:string|null}){
  const [context,setContext]=useState<BuilderContext>(initial);
  const [history,setHistory]=useState<HistoryEntry[]>([]);
  const [sessionId,setSessionId]=useState(initialSessionId);
  const [message,setMessage]=useState('');
  const [saveStatus,setSaveStatus]=useState<SaveStatus>('idle');
  const [editingQuestionId,setEditingQuestionId]=useState<string|null>(null);
  const [pending,startTransition]=useTransition();
  const router=useRouter();
  const step=useMemo(()=>ruleBasedBuilderEngine.getNextStep(context),[context]);

  const answer=(value:unknown,label?:string)=>{if(!step)return;let actual=value;if(step.id==='introText'&&!value)actual=defaultIntroText(context.anonymous??true);if(step.id==='completionText'&&!value)actual=defaultCompletionText;setContext(ruleBasedBuilderEngine.applyAnswer(context,step.id,actual));setHistory(entries=>[...entries,{step,value:actual,label:label??labels[String(actual)]??String(actual)}]);setMessage('');setSaveStatus('idle');};
  const edit=(index:number)=>{const entry=history[index];setContext(current=>reopenBuilderStep(current,entry.step.id));setHistory(entries=>entries.slice(0,index));setEditingQuestionId(null);setSaveStatus('idle');};
  const save=()=>{setSaveStatus('saving');setMessage('');startTransition(async()=>{const result=await saveBuilderSessionAction(sessionId,context,step?.id??'summary');if(result.sessionId)setSessionId(result.sessionId);if(result.error){setSaveStatus('error');setMessage('保存できませんでした。入力内容は保持されています。');}else{setSaveStatus('saved');setMessage('保存しました');}});};
  const complete=()=>startTransition(async()=>{const result=await completeBuilderAction(sessionId,context);if(result.surveyId)router.push(`/admin/surveys/${result.surveyId}`);else setMessage(result.error??'作成できませんでした。');});
  const version=useMemo(()=>buildBuilderPreviewVersion(context),[context]);
  const updateQuestion=useCallback((questionId:string,patch:Partial<SurveyQuestion>)=>{setContext(current=>({...current,questions:current.questions?.map(question=>question.id===questionId?{...question,...patch}:question)}));setSaveStatus('idle');},[]);
  const focusCurrent=()=>window.setTimeout(()=>document.getElementById('current-builder-question')?.scrollIntoView({behavior:'smooth',block:'center'}),0);
  const editFromPreview=useCallback((target:string)=>{const resolved=resolveBuilderPreviewTarget(target,context);if(!resolved)return;if(resolved.kind==='question'){setEditingQuestionId(resolved.questionId);window.setTimeout(()=>document.getElementById(`builder-question-${resolved.questionId}`)?.scrollIntoView({behavior:'smooth',block:'center'}),0);return;}const index=history.findIndex(entry=>entry.step.id===resolved.stepId);setContext(current=>reopenBuilderStep(current,resolved.stepId));if(index>=0)setHistory(entries=>entries.slice(0,index));setEditingQuestionId(null);setSaveStatus('idle');focusCurrent();},[context,history]);

  return <div className="builder-preview-layout"><div className="builder-page"><header className="builder-page-header"><p className="eyebrow">アンケート設計</p><h1>新しいアンケートを作成</h1><p>お客様から聞いた内容を選ぶだけで、構成を整理します。</p></header><div className="builder-action-bar" aria-label="作成操作"><div className="builder-progress"><span className="status-dot" aria-hidden="true"/><div><strong>{ruleBasedBuilderEngine.isComplete(context)?'作成内容が確定しました':'作成途中'}</strong><small>{context.storeName||'店舗・医院名はまだ未入力です'}</small></div></div><div className="builder-actions"><button className="btn secondary" type="button" disabled={pending||saveStatus==='saving'} onClick={save}>{saveStatus==='saving'?'保存しています...':'下書き保存'}</button></div></div>{message&&<p className={saveStatus==='error'?'save-message error':'save-message notice'} role={saveStatus==='error'?'alert':'status'}>{message}</p>}<main className="builder-chat"><div className="chat-log" aria-live="polite">{history.map((entry,index)=><div key={`${entry.step.id}-${index}`} className="history-block"><div className="history-label">過去の質問</div><div className="chat-bubble system">{entry.step.question}</div><div className="chat-answer"><div><small>回答</small><span>{entry.label}</span></div><button type="button" onClick={()=>edit(index)}>変更</button></div></div>)}{editingQuestionId&&context.questions?.some(question=>question.id===editingQuestionId)&&<QuestionQuickEditor question={context.questions.find(question=>question.id===editingQuestionId)!} update={patch=>updateQuestion(editingQuestionId,patch)} close={()=>setEditingQuestionId(null)}/>} {step&&<section className="current-step" aria-labelledby="current-builder-question"><p className="current-label">現在の質問</p><div className="current-question-card"><h2 id="current-builder-question">{step.question}</h2><details><summary>この質問について</summary><p>{step.reason}</p></details><StepInput key={step.id} step={step} context={context} answer={answer} complete={complete} pending={pending} editQuestion={setEditingQuestionId}/></div></section>}</div></main></div><LiveSurveyPreview name={context.storeName??'店舗・医院名'} version={version} onEdit={editFromPreview} className="builder-live-preview"/></div>;
}

function StepInput({step,context,answer,complete,pending,editQuestion}:{step:BuilderStep;context:BuilderContext;answer:(value:unknown,label?:string)=>void;complete:()=>void;pending:boolean;editQuestion:(id:string)=>void}){
  const [text,setText]=useState('');
  if(step.inputType==='choice')return <div className="builder-options">{step.options?.map(o=><button className="option-card" type="button" key={o.value} onClick={()=>answer(o.value,o.label)}><strong>{o.label}</strong>{o.description&&<small>{o.description}</small>}<span className="option-arrow" aria-hidden="true">›</span></button>)}</div>;
  const format=(q:NonNullable<BuilderContext['questions']>[number])=>q.type==='rating_10'?`スコアリング（${q.settings.maxScore??10}段階）`:q.type==='textarea'?'長文テキスト':q.type==='text'?'短文テキスト':q.type==='multiple_choice'?'チェックボックス':q.settings.presentation==='select'?'プルダウン':'ラジオボタン';
  if(step.inputType==='question_review')return <div className="stack question-review-list">{context.questions?.map((q,i)=><div className="question-review" key={q.id}><strong>Q{i+1} {q.title}</strong><span>{format(q)} · {q.required?'必須':'任意'}</span>{q.options.length>0&&<small>{q.options.map(o=>o.label).join(' / ')}</small>}{q.type==='rating_10'&&<small>{q.settings.minLabel??'非常に不満'} 〜 {q.settings.maxLabel??'非常に満足'}</small>}<button className="question-edit-link" type="button" onClick={()=>editQuestion(q.id)}>この質問を編集</button></div>)}<button className="btn" type="button" onClick={()=>answer('confirmed','全質問を確認しました')}>この構成で進む</button></div>;
  if(step.inputType==='summary')return <div className="summary-card"><dl><dt>店舗名</dt><dd>{context.storeName}</dd><dt>業種</dt><dd>{labels[context.businessType??'']}</dd><dt>目的</dt><dd>{labels[context.purpose??'']??context.purposeDetail}</dd><dt>匿名</dt><dd>{context.anonymous?'はい':'いいえ'}</dd><dt>質問数</dt><dd>{context.questions?.length}問</dd>{context.questions?.map((q,i)=><div key={q.id} className="summary-question"><dt>Q{i+1}</dt><dd><strong>{q.title}</strong><br/>{format(q)} · {q.required?'必須':'任意'}{q.options.length>0&&<><br/>選択肢: {q.options.map(o=>o.label).join(' / ')}</>}{q.type==='rating_10'&&<><br/>{q.settings.minLabel??'非常に不満'} 〜 {q.settings.maxLabel??'非常に満足'}</>}</dd></div>)}<dt>Google口コミ</dt><dd>{context.googleReviewEnabled?'全回答者に表示':'使用しない'}（URL: {context.googleReviewUrl?'設定済み':'未設定'}）</dd><dt>デザイン</dt><dd>Theme: {context.themeId??'自動選択'} / メインカラー: {context.mainColor}</dd></dl><button className="btn" type="button" disabled={pending} onClick={complete}>{pending?'作成中…':'この内容で作成'}</button></div>;
  const suggested=step.id==='introText'?defaultIntroText(context.anonymous??true):step.id==='completionText'?defaultCompletionText:step.id==='mainColor'?'#5E969E':'';
  return <form className="answer-form" onSubmit={event=>{event.preventDefault();answer(text||suggested,text||suggested)}}>{step.inputType==='color'?<input aria-label="メインカラー" type="color" value={text||suggested} onChange={event=>setText(event.target.value)}/>:<textarea aria-label={step.question} rows={step.id==='introText'||step.id==='completionText'?4:2} value={text||suggested} onChange={event=>setText(event.target.value)} placeholder={step.inputType==='url'?'https://...':'入力してください'}/>}<button className="btn" type="submit">{suggested&&text===''?'おすすめのまま':'回答する'}</button></form>;
}

function QuestionQuickEditor({question,update,close}:{question:SurveyQuestion;update:(patch:Partial<SurveyQuestion>)=>void;close:()=>void}){
  const choice=question.type==='single_choice'||question.type==='multiple_choice';
  const changeType=(type:QuestionType)=>update({type,settings:type==='rating_10'?{...question.settings,maxScore:question.settings.maxScore??10}:type==='single_choice'?{...question.settings,presentation:question.settings.presentation??'radio'}:{},options:type==='single_choice'||type==='multiple_choice'?(question.options.length?question.options:[{label:'選択肢1',value:'option-1',sortOrder:0},{label:'選択肢2',value:'option-2',sortOrder:1}]):[]});
  return <section id={`builder-question-${question.id}`} className="current-step question-quick-editor" aria-labelledby={`builder-question-title-${question.id}`}><p className="current-label">プレビューから質問を編集中</p><div className="current-question-card"><div className="question-editor-heading"><h2 id={`builder-question-title-${question.id}`}>質問を修正</h2><button type="button" onClick={close}>× 閉じる</button></div><label>質問文<input value={question.title} onChange={event=>update({title:event.target.value})}/></label><div className="question-editor-grid"><label>回答形式<select value={question.type} onChange={event=>changeType(event.target.value as QuestionType)}><option value="text">短文テキスト</option><option value="textarea">長文テキスト</option><option value="single_choice">単一選択</option><option value="multiple_choice">複数選択</option><option value="rating_10">スコアリング</option></select></label><label className="question-required"><input type="checkbox" checked={question.required} onChange={event=>update({required:event.target.checked})}/> 必須回答にする</label></div>{choice&&<label>選択肢（1行に1つ）<textarea rows={5} value={question.options.map(option=>option.label).join('\n')} onChange={event=>update({options:event.target.value.split('\n').map((label,index)=>({label,value:`option-${index+1}`,sortOrder:index}))})}/></label>}{question.type==='rating_10'&&<><fieldset className="score-choice"><legend>点数</legend><label><input type="radio" checked={question.settings.maxScore===5} onChange={()=>update({settings:{...question.settings,maxScore:5}})}/> 5点</label><label><input type="radio" checked={question.settings.maxScore!==5} onChange={()=>update({settings:{...question.settings,maxScore:10}})}/> 10点</label></fieldset><div className="question-editor-grid"><label>最低点ラベル<input value={question.settings.minLabel??''} onChange={event=>update({settings:{...question.settings,minLabel:event.target.value}})}/></label><label>最高点ラベル<input value={question.settings.maxLabel??''} onChange={event=>update({settings:{...question.settings,maxLabel:event.target.value}})}/></label></div></>}</div></section>;
}
