'use client';
import {useCallback,useEffect,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {saveBuilderSessionAction} from '@/app/actions';
import {QuestionBuilder} from '@/components/admin/QuestionBuilder';
import {ReviewSettings} from '@/components/admin/ReviewSettings';
import {DesignFields} from '@/components/admin/DesignFields';
import {LiveSurveyPreview} from '@/components/admin/LiveSurveyPreview';
import {builderConfig,industries,prefectures,validateReviewSettings} from '@/lib/builder/settings';
import {cloneTemplate} from '@/lib/builder/templates';
import {getThemeTemplate,themeIdForBusiness} from '@/lib/theme/templates';
import {validateQuestion} from '@/lib/survey';
import type {BuilderContext,BuilderTemplate,SurveyConfig,SurveyQuestion} from '@/types/database';
const steps=['基本情報','質問作成','Google口コミ設定','デザイン設定','プレビュー・公開'];
export function SurveyWizard({initial={},initialSessionId=null}:{initial?:BuilderContext;initialSessionId?:string|null}) {
  const router=useRouter();
  const [context,setContext]=useState<BuilderContext>(()=>({...initial,businessType:initial.businessType??'other',purpose:initial.purpose??'satisfaction',startingPoint:initial.startingPoint??'decided',anonymous:initial.anonymous??true,config:builderConfig(initial)}));
  const [step,setStep]=useState(0),[session,setSession]=useState(initialSessionId),[revision,setRevision]=useState(0),[savedRevision,setSavedRevision]=useState(0),[message,setMessage]=useState(''),[pending,start]=useTransition();
  const dirty=revision!==savedRevision;
  const config=builderConfig(context);
  const [assetId]=useState(()=>crypto.randomUUID());
  const change=useCallback((patch:Partial<BuilderContext>)=>{setContext(c=>({...c,...patch}));setRevision(r=>r+1);setMessage('')},[]);
  const design=useCallback((patch:Partial<SurveyConfig>)=>{setContext(c=>({...c,config:{...c.config,...patch}}));setRevision(r=>r+1);setMessage('')},[]);
  const questionsChanged=useCallback((questions:SurveyQuestion[])=>{setContext(c=>{if(JSON.stringify(c.questions??[])===JSON.stringify(questions))return c;return {...c,questions}});setRevision(r=>r+1)},[]);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
  const canonical=():BuilderContext=>({...context,heroTitle:config.heroTitle||config.title,heroSubtitle:config.heroSubtitle,introText:config.introText||config.description,questionFontSize:config.questionFontSize??17,mainColor:config.primaryColor,logoMode:config.logoMode??'none',logoUrl:config.logoUrl,googleReviewEnabled:config.googleReviewMode!=='disabled',googleReviewMode:config.googleReviewMode,googleReviewRule:config.googleReviewRule,googleReviewUrl:config.googleReviewUrl,completionText:config.completionText,questionsConfirmed:true,config});
  const validate=()=>{if(!context.storeName?.trim())return '店舗・医院名を入力してください。';if(!context.businessType)return '業種を選択してください。';if(!context.questions?.length)return '質問を1問以上追加してください。';for(const q of context.questions){const error=validateQuestion(q);if(error)return error;}if(!config.title.trim())return 'タイトルを入力してください。';return validateReviewSettings(config,context.questions)};
  const save=()=>{const snapshot=canonical(),rev=revision;start(async()=>{try{const result=await saveBuilderSessionAction(session,snapshot,String(step));if(result.error){setMessage(`保存失敗：${result.error}`);return}if(result.sessionId)setSession(result.sessionId);setSavedRevision(rev);setMessage('保存済み')}catch{setMessage('保存失敗：通信環境を確認してください。')}})};
  const complete=()=>{const error=validate();if(error){setMessage(error);return;}start(async()=>{try{const response=await fetch('/api/admin/surveys/create-from-builder',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:session,context:canonical()})});const result=await response.json();if(!response.ok||!result.surveyId){setMessage(result.error??'作成できませんでした。');return;}setSavedRevision(revision);router.push(`/admin/surveys/${result.surveyId}#publish-settings`)}catch{setMessage('通信エラーが発生しました。入力内容は保持されています。')}})};
  const template=(value:BuilderTemplate)=>{const business=value==='restaurant_standard'?'restaurant':value==='salon_standard'?'salon':'clinic';const theme=getThemeTemplate(themeIdForBusiness(business));change({template:value,questions:value==='custom'?[]:cloneTemplate(value),config:{...config,...(value==='custom'?{}:theme.config),themeId:theme.id,title:theme.config.heroTitle,googleReviewMode:'disabled',googleReviewRule:null,reviewTextQuestionId:null}})};
  const version={id:'wizard-preview',surveyId:'wizard-preview',version:1,status:'draft' as const,config,questions:context.questions??[]};
  return <div className="preview-first-layout"><div className="editor-panel stack"><header><h1>新しいアンケートを作成</h1><p>基本情報から公開まで、5つのステップで設定します。</p></header><nav className="editor-section-nav" aria-label="作成ステップ">{steps.map((label,i)=><button type="button" className={step===i?'btn':'btn secondary'} aria-current={step===i?'step':undefined} key={label} onClick={()=>setStep(i)}>{i+1}. {label}</button>)}</nav><div className="row"><span role="status">{pending?'保存中':dirty?'未保存の変更あり':'保存済み'}</span><button type="button" className="btn secondary" disabled={pending} onClick={save}>下書き保存</button></div>{message&&<p role="status" className="notice">{message}</p>}
    <div hidden={step!==0} className="card stack admin-form-card"><h2>STEP1 基本情報</h2><label className="field">店舗・医院名<input value={context.storeName??''} onChange={e=>change({storeName:e.target.value})}/></label><label className="field">業種<select value={context.industry??({clinic:'クリニック',restaurant:'飲食店',salon:'美容室',other:'その他'}[context.businessType??'other'])} onChange={e=>change({industry:e.target.value,businessType:e.target.value==='クリニック'?'clinic':e.target.value==='飲食店'?'restaurant':['美容室','サロン'].includes(e.target.value)?'salon':'other'})}>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">業態<input placeholder="例：眼科、居酒屋、カフェ" value={context.businessCategory??config.businessCategory??''} onChange={e=>change({businessCategory:e.target.value})}/></label><label className="field">都道府県<select value={context.prefecture??config.prefecture??''} onChange={e=>change({prefecture:e.target.value})}><option value="">選択してください</option>{prefectures.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">アンケートタイトル<input value={config.heroTitle??config.title} onChange={e=>design({title:e.target.value,heroTitle:e.target.value})}/></label><label className="field">説明文<textarea value={config.description} onChange={e=>design({description:e.target.value,heroSubtitle:e.target.value})}/></label><label className="field">匿名／記名<select value={String(config.anonymous??true)} onChange={e=>{design({anonymous:e.target.value==='true'});change({anonymous:e.target.value==='true'})}}><option value="true">匿名</option><option value="false">記名（必要な情報は質問で追加）</option></select></label><label className="field">質問テンプレート<select value={context.template??''} onChange={e=>{if(context.questions?.length&&!window.confirm('現在の質問をテンプレートで置き換えますか？'))return;template(e.target.value as BuilderTemplate)}}><option value="" disabled>選択してください</option><option value="clinic_standard">クリニック標準</option><option value="restaurant_standard">飲食店標準</option><option value="salon_standard">美容室標準</option><option value="custom">自分で作る</option></select></label></div>
    <div hidden={step!==1}><QuestionBuilder key={context.template??'initial'} surveyId="" versionId="" initial={context.questions??[]} onChange={questionsChanged} localOnly/></div>
    <div hidden={step!==2} className="card stack admin-form-card"><h2>STEP3 Google口コミ設定</h2><ReviewSettings config={config} questions={version.questions} onChange={design}/></div>
    <div hidden={step!==3} className="card stack admin-form-card"><h2>STEP4 デザイン設定</h2><DesignFields config={config} onChange={design} surveyId={assetId}/></div>
    <div hidden={step!==4} className="card stack admin-form-card"><h2>STEP5 プレビュー・公開</h2><p>{context.storeName} ／ {context.industry} ／ {context.businessCategory} ／ {context.prefecture}</p><p>質問数：{version.questions.length}問</p><p>プレビューの「本編」「サンクス」「口コミ導線」を確認してください。作成後の公開設定から、公開URLとQRコードを発行できます。</p><button type="button" className="btn" disabled={pending} onClick={complete}>この内容で作成して公開設定へ</button></div>
    <div className="row"><button type="button" className="btn secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)}>前へ</button><button type="button" className="btn" disabled={step===4} onClick={()=>setStep(s=>s+1)}>次へ</button></div>
  </div><LiveSurveyPreview name={context.storeName||'店舗・医院名'} version={version}/></div>;
}
