'use server';
import { revalidatePath } from 'next/cache'; import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server'; import { defaultConfig, normalizeQuestionFontSize, slugify, validateQuestion, validateSlug } from '@/lib/survey'; import type { BuilderContext, SurveyQuestion } from '@/types/database';
import { ruleBasedBuilderEngine } from '@/lib/builder/engine';
import { getThemeTemplate, themeIdForBusiness } from '@/lib/theme/templates';
import {completionSettingsConfig,mergeSurveyConfig} from '@/lib/config';
import {canDemoteAdmin} from '@/lib/auth/security';
import {parseCompletionRulesJson,validateRulesForQuestions} from '@/lib/completion-validation';
import {appUrl} from '@/lib/env';
async function staff(){ const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user) throw new Error('ログインが必要です。'); const {data:p}=await s.from('profiles').select('role,is_active').eq('id',user.id).single(); if(!p)throw new Error('権限がありません。'); if(!p.is_active)throw new Error('管理者の承認待ちです。'); if(p.role!=='admin'&&p.role!=='sales')throw new Error('権限がありません。'); return {s,user,p}; }
async function isActiveSurvey(s:Awaited<ReturnType<typeof createClient>>,id:string){const {data}=await s.from('surveys').select('id').eq('id',id).neq('status','archived').maybeSingle();return Boolean(data)}
export async function loginAction(_:unknown,form:FormData){ const s=await createClient(); const {error}=await s.auth.signInWithPassword({email:String(form.get('email')||''),password:String(form.get('password')||'')}); if(error)return {error:'メールアドレスまたはパスワードを確認してください。'}; redirect('/admin'); }
export async function logoutAction(){ const s=await createClient(); await s.auth.signOut(); redirect('/login'); }
export async function createSurveyAction(_:unknown,form:FormData){ try{ const {s,user}=await staff(); const name=String(form.get('name')||'').trim(); const slug=String(form.get('slug')||slugify(name)); const industry=String(form.get('industry')||'').trim(); if(!name||!validateSlug(slug))return {error:'名称と半角英数字のslugを入力してください。'}; const {data:survey,error}=await s.from('surveys').insert({name,slug,industry,owner_user_id:user.id,created_by:user.id,updated_by:user.id}).select('id').single(); if(error)return {error:error.code==='23505'?'このslugは使用済みです。':'作成に失敗しました。'}; const config={...defaultConfig,title:`${name} お客様アンケート`}; const {data:v,error:ve}=await s.from('survey_versions').insert({survey_id:survey.id,version:1,status:'draft',config,created_by:user.id}).select('id').single(); if(ve)throw ve; await s.from('surveys').update({current_draft_version_id:v.id}).eq('id',survey.id); redirect(`/admin/surveys/${survey.id}`); }catch(e){return {error:e instanceof Error?e.message:'作成に失敗しました。'};} }
export async function saveSurveyAction(id:string,_:unknown,form:FormData){ try{ const {s,user}=await staff();if(!await isActiveSurvey(s,id))return {error:'アンケートを更新できませんでした。'}; const name=String(form.get('name')||'').trim(),slug=String(form.get('slug')||'').trim(); if(!name||!validateSlug(slug))return {error:'名称と有効なslugを入力してください。'}; const {error}=await s.from('surveys').update({name,slug,industry:String(form.get('industry')||''),updated_by:user.id}).eq('id',id).neq('status','archived'); if(error)return {error:error.code==='23505'?'このslugは使用済みです。':'保存に失敗しました。'}; revalidatePath(`/admin/surveys/${id}`); return {success:'基本情報を保存しました。'}; }catch(e){return {error:e instanceof Error?e.message:'保存に失敗しました。'};} }
export async function saveConfigAction(surveyId:string,versionId:string,_:unknown,form:FormData){ try{ const {s}=await staff();if(!await isActiveSurvey(s,surveyId))return {error:'アンケートを更新できませんでした。'}; const val=(k:string)=>String(form.get(k)||'').trim(); const themeId=val('themeId') as 'clinic-clean'|'restaurant-clean'|'salon-clean';const template=getThemeTemplate(themeId);const {data:current}=await s.from('survey_versions').select('config').eq('id',versionId).eq('survey_id',surveyId).eq('status','draft').single();if(!current)return {error:'下書きが見つかりません。'};const edited={title:val('title'),description:val('description'),introText:val('introText'),anonymousText:val('anonymousText'),completionText:val('completionText'),submitLabel:val('submitLabel')||'回答を送信',buttonLabel:val('submitLabel')||'回答を送信',primaryColor:val('primaryColor')||template.config.primaryColor,secondaryColor:val('secondaryColor')||template.config.secondaryColor,backgroundColor:val('backgroundColor')||template.config.backgroundColor,accentColor:val('accentColor')||template.config.accentColor,heroOverlayColor:val('heroOverlayColor')||template.config.heroOverlayColor,heroTextColor:val('heroTextColor')||template.config.heroTextColor,buttonBackground:val('buttonBackground')||template.config.buttonBackground,buttonTextColor:val('buttonTextColor')||template.config.buttonTextColor,cardBackground:val('cardBackground')||template.config.cardBackground,logoBadgeBackground:val('logoBadgeBackground')||template.config.logoBadgeBackground,themeId,heroBackgroundType:val('heroBackgroundType')==='solid' as const?'solid' as const:'soft-gradient' as const,heroTitle:val('heroTitle')||val('title'),heroSubtitle:val('heroSubtitle')||val('description'),logoMode:(val('logoMode')||'icon') as 'none'|'icon'|'upload',cardRadius:Number(val('cardRadius')||18),questionFontSize:normalizeQuestionFontSize(val('questionFontSize')),logoUrl:val('logoUrl')||null,iconUrl:val('iconUrl')||null}; for(const k of ['logoUrl','iconUrl'] as const){if(edited[k])try{new URL(edited[k]!)}catch{return {error:`${k}のURLが不正です。`};}} const config=mergeSurveyConfig(current.config as any,edited);const {error}=await s.from('survey_versions').update({config}).eq('id',versionId).eq('survey_id',surveyId).eq('status','draft'); if(error)throw error; revalidatePath(`/admin/surveys/${surveyId}`); return {success:'下書きを保存しました。公開版は変更されていません。'}; }catch(e){return {error:e instanceof Error?e.message:'保存に失敗しました。'};} }
export async function saveQuestionsAction(surveyId:string,versionId:string,questions:SurveyQuestion[]){ const {s}=await staff();if(!await isActiveSurvey(s,surveyId))return {error:'アンケートを更新できませんでした。'}; for(const q of questions){const error=validateQuestion(q);if(error)return {error};} const {error:de}=await s.from('questions').delete().eq('survey_version_id',versionId); if(de)return {error:'質問の保存に失敗しました。'}; for(let i=0;i<questions.length;i++){const q=questions[i]; const {data:created,error}=await s.from('questions').insert({survey_version_id:versionId,type:q.type,title:q.title.trim(),description:q.description.trim(),required:q.required,sort_order:i,settings:q.settings}).select('id').single(); if(error)return {error:'質問の保存に失敗しました。'}; if(q.type==='single_choice'||q.type==='multiple_choice'){const opts=q.options.filter(o=>o.label.trim()).map((o,n)=>({question_id:created.id,label:o.label.trim(),value:o.value.trim()||`option-${n+1}`,sort_order:n})); const {error:oe}=await s.from('question_options').insert(opts); if(oe)return {error:'選択肢の保存に失敗しました。'};}} revalidatePath(`/admin/surveys/${surveyId}`); return {success:'質問を保存しました。公開版は変更されていません。'}; }
export async function publishAction(id:string){ const {s}=await staff(); const {error}=await s.rpc('publish_survey',{p_survey_id:id}); if(error)return {error:error.message}; revalidatePath('/admin'); revalidatePath(`/admin/surveys/${id}`); return {success:'公開しました。新しい下書きも作成済みです。'}; }
export async function unpublishAction(id:string){ const {s,user}=await staff(); const {error}=await s.from('surveys').update({status:'unpublished',updated_by:user.id}).eq('id',id).neq('status','archived'); if(error)return {error:'非公開にできませんでした。'}; revalidatePath('/admin'); return {success:'非公開にしました。'}; }
export async function archiveAction(id:string){ try{const {s,user,p}=await staff(); if(p.role!=='admin')return {error:'アンケートの削除は管理者のみ実行できます。'}; const {data,error}=await s.from('surveys').update({status:'archived',archived_at:new Date().toISOString(),updated_by:user.id}).eq('id',id).neq('status','archived').select('id').maybeSingle(); if(error||!data)return {error:'アンケートを削除できませんでした。'}; revalidatePath('/admin');revalidatePath(`/admin/surveys/${id}`);return {success:'アンケートを削除しました。'};}catch{return {error:'アンケートを削除できませんでした。'};} }
export async function restoreSurveyAction(id:string){ try{const {s,user,p}=await staff();if(p.role!=='admin')return {error:'アンケートの復元は管理者のみ実行できます。'};const {data,error}=await s.from('surveys').update({status:'unpublished',archived_at:null,updated_by:user.id}).eq('id',id).eq('status','archived').select('id').maybeSingle();if(error||!data)return {error:'アンケートを復元できませんでした。'};revalidatePath('/admin');revalidatePath(`/admin/surveys/${id}`);return {success:'アンケートを非公開状態で復元しました。'};}catch{return {error:'アンケートを復元できませんでした。'};} }
export async function duplicateSurveyAction(id:string,_:unknown,form:FormData){ try{const {s,user}=await staff(); const {data:src}=await s.from('surveys').select('*,survey_versions!surveys_current_draft_version_id_fkey(*,questions(*,question_options(*)))').eq('id',id).neq('status','archived').single(); if(!src)throw new Error('複製元が見つかりません。'); const name=String(form.get('name')||`${src.name} のコピー`),slug=String(form.get('slug')||`${src.slug}-copy`); if(!validateSlug(slug))return {error:'slugが不正です。'}; const {data:n,error}=await s.from('surveys').insert({name,slug,industry:src.industry,owner_user_id:user.id,created_by:user.id,updated_by:user.id}).select('id').single(); if(error)return {error:'複製先のslugが使用済みです。'}; const source=(src as any).survey_versions; const {data:v}=await s.from('survey_versions').insert({survey_id:n.id,version:1,status:'draft',config:{...source.config,title:`${name} お客様アンケート`},created_by:user.id}).select('id').single(); for(const q of (source.questions??[]).sort((a:any,b:any)=>a.sort_order-b.sort_order)){const {data:nq}=await s.from('questions').insert({survey_version_id:v!.id,type:q.type,title:q.title,description:q.description,required:q.required,sort_order:q.sort_order,settings:q.settings}).select('id').single(); if(q.question_options?.length)await s.from('question_options').insert(q.question_options.map((o:any)=>({question_id:nq!.id,label:o.label,value:o.value,sort_order:o.sort_order})));} await s.from('surveys').update({current_draft_version_id:v!.id}).eq('id',n.id); redirect(`/admin/surveys/${n.id}`);}catch(e){return {error:e instanceof Error?e.message:'複製に失敗しました。'};} }
export async function updateRoleAction(profileId:string,_:unknown,form:FormData){const {s,p}=await staff();if(p.role!=='admin')return {error:'管理者のみ変更できます。'};const role=String(form.get('role'));if(role!=='admin'&&role!=='sales')return {error:'権限が不正です。'};const [{data:target},{count}]=await Promise.all([s.from('profiles').select('role').eq('id',profileId).single(),s.from('profiles').select('id',{count:'exact',head:true}).eq('role','admin')]);if(!target)return {error:'対象ユーザーが見つかりません。'};if(!canDemoteAdmin(target.role,role,count??0))return {error:'最後の管理者は営業権限へ変更できません。'};const {error}=await s.from('profiles').update({role}).eq('id',profileId);if(error)return {error:'権限を更新できませんでした。'};revalidatePath('/admin/users');return {success:'権限を更新しました。'};}

export async function approveUserAction(profileId:string){try{const {s,p}=await staff();if(p.role!=='admin')return {error:'管理者のみ承認できます。'};const {data,error}=await s.from('profiles').update({is_active:true}).eq('id',profileId).eq('is_active',false).select('id').maybeSingle();if(error||!data)return {error:'対象ユーザーを承認できませんでした。'};revalidatePath('/admin/users');return {success:'利用を許可しました。'};}catch(e){return {error:e instanceof Error?e.message:'対象ユーザーを承認できませんでした。'};}}

export async function sendPasswordResetAction(profileId:string){try{const {s,p}=await staff();if(p.role!=='admin')return {error:'管理者のみ実行できます。'};const {data:target}=await s.from('profiles').select('email').eq('id',profileId).single();if(!target?.email)return {error:'対象ユーザーを確認できませんでした。'};const {error}=await s.auth.resetPasswordForEmail(target.email,{redirectTo:`${appUrl()}/auth/confirm?next=/admin/account/update-password`});if(error)return {error:'再設定メールを送信できませんでした。'};return {success:'アカウントが存在する場合、再設定メールを送信しました。'};}catch{return {error:'再設定メールを送信できませんでした。'};}}

export async function saveBuilderSessionAction(sessionId:string|null,context:BuilderContext,currentStep:string){
  try { const {s,user}=await staff(); const payload={user_id:user.id,status:'in_progress',context,current_step:currentStep,updated_at:new Date().toISOString()};
    if(sessionId){const {error}=await s.from('builder_sessions').update(payload).eq('id',sessionId).eq('status','in_progress');if(error)throw error;return {success:'作成途中として保存しました。',sessionId};}
    const {data,error}=await s.from('builder_sessions').insert(payload).select('id').single();if(error)throw error;return {success:'作成途中として保存しました。',sessionId:data.id as string};
  } catch(e){return {error:e instanceof Error?e.message:'途中保存に失敗しました。'};}
}

export async function completeBuilderAction(sessionId:string|null,context:BuilderContext){
  try { const {s,user}=await staff(); const missing=ruleBasedBuilderEngine.getMissingFields(context);if(missing.length)return {error:`未確定の項目があります: ${missing.join(', ')}`};
    const name=context.storeName!.trim(),base=slugify(name)||`survey-${Date.now()}`;let slug=base;
    for(let n=2;n<100;n++){const {data}=await s.from('surveys').select('id').eq('slug',slug).maybeSingle();if(!data)break;slug=`${base}-${n}`;}
    const {data:survey,error}=await s.from('surveys').insert({name,slug,industry:context.businessType,owner_user_id:user.id,created_by:user.id,updated_by:user.id}).select('id').single();if(error)throw error;
    const themeId=context.themeId??themeIdForBusiness(context.businessType!);const theme=getThemeTemplate(themeId);const heroTitle=context.heroTitle??theme.config.heroTitle;const config={...defaultConfig,...theme.config,themeId,title:heroTitle,heroTitle,heroSubtitle:theme.config.heroSubtitle,introText:context.introText!,anonymousText:context.anonymous?'こちらのアンケートは匿名です。':'回答内容は運営者が確認します。',completionText:context.completionText!,questionFontSize:normalizeQuestionFontSize(context.questionFontSize),primaryColor:context.mainColor!,logoMode:context.logoMode,logoUrl:context.logoUrl??null,googleReviewUrl:context.googleReviewEnabled?context.googleReviewUrl??null:null};
    const {data:version,error:versionError}=await s.from('survey_versions').insert({survey_id:survey.id,version:1,status:'draft',config,created_by:user.id}).select('id').single();if(versionError)throw versionError;
    for(const [index,q] of context.questions!.entries()){const {data:created,error:qError}=await s.from('questions').insert({survey_version_id:version.id,type:q.type,title:q.title,description:q.description,required:q.required,sort_order:index,settings:q.settings}).select('id').single();if(qError)throw qError;if(q.options.length){const {error:oError}=await s.from('question_options').insert(q.options.map((o,n)=>({question_id:created.id,label:o.label,value:o.value,sort_order:n})));if(oError)throw oError;}}
    await s.from('surveys').update({current_draft_version_id:version.id}).eq('id',survey.id);if(sessionId)await s.from('builder_sessions').update({status:'completed',survey_id:survey.id,context,current_step:'completed',updated_at:new Date().toISOString()}).eq('id',sessionId);
    return {success:'作成内容が確定しました。',surveyId:survey.id as string};
  }catch(e){return {error:e instanceof Error?e.message:'アンケートを作成できませんでした。'};}
}

export async function saveCompletionSettingsAction(surveyId:string,versionId:string,_:unknown,form:FormData){try{const {s}=await staff();if(!await isActiveSurvey(s,surveyId))return {error:'アンケートを更新できませんでした。'};const reviewUrl=String(form.get('googleReviewUrl')||'').trim(),reviewMode=form.get('googleReviewMode')==='all'?'all':'disabled';if(reviewUrl)try{new URL(reviewUrl)}catch{return {error:'Google口コミURLが不正です。'}};const rules=parseCompletionRulesJson(String(form.get('completionRules')||'[]'));const [{data},{data:rows}]=await Promise.all([s.from('survey_versions').select('config').eq('id',versionId).eq('survey_id',surveyId).eq('status','draft').single(),s.from('questions').select('id,type,title,description,required,sort_order,settings,question_options(id,label,value,sort_order)').eq('survey_version_id',versionId)]);if(!data)return {error:'下書きが見つかりません。'};const questions=(rows??[]).map((q:any)=>({id:q.id,type:q.type,title:q.title,description:q.description,required:q.required,sortOrder:q.sort_order,settings:q.settings??{},options:(q.question_options??[]).map((o:any)=>({id:o.id,label:o.label,value:o.value,sortOrder:o.sort_order}))}));const validation=validateRulesForQuestions(rules,questions);if(validation)return {error:validation};if(reviewMode==='all'&&!reviewUrl)return {error:'Google口コミURLを入力してください。'};const config=completionSettingsConfig(data.config,reviewMode,reviewUrl,rules);const {error}=await s.from('survey_versions').update({config}).eq('id',versionId).eq('survey_id',surveyId).eq('status','draft');if(error)throw error;revalidatePath(`/admin/surveys/${surveyId}`);return {success:'回答後設定を保存しました。'}}catch(e){return {error:e instanceof Error?e.message:'回答後設定を保存できませんでした。'}}}
