-- Google口コミURLは実URL確認後、管理画面で設定してください。
do $$ declare sid uuid; vid uuid; qid uuid; begin
sid:='10000000-0000-4000-8000-000000000001';vid:='11000000-0000-4000-8000-000000000001';
insert into surveys(id,name,slug,industry,status,current_draft_version_id) values(sid,'水谷眼科診療所','mizutani-eye','眼科','draft',null) on conflict(id) do update set name=excluded.name;
insert into survey_versions(id,survey_id,version,status,config) values(vid,sid,1,'draft','{"title":"水谷眼科診療所 患者様アンケート","description":"今後の診療・サービス向上のため、ご意見をお聞かせください。","introText":"お忙しいところ恐れ入りますが、アンケートにご協力ください。","anonymousText":"このアンケートは匿名です。氏名・連絡先は取得しません。","completionText":"ご回答ありがとうございました。いただいたご意見は、今後より良い診療環境づくりに活用させていただきます。","submitLabel":"回答を送信","primaryColor":"#147d74","backgroundColor":"#f2faf8","logoUrl":null,"iconUrl":null,"googleReviewUrl":null}'::jsonb) on conflict(id) do nothing;update surveys set current_draft_version_id=vid where id=sid;
if not exists(select 1 from questions where survey_version_id=vid) then
insert into questions(survey_version_id,type,title,required,sort_order) values(vid,'single_choice','性別を教えてください。',false,0) returning id into qid;insert into question_options(question_id,label,value,sort_order) values(qid,'男性','male',0),(qid,'女性','female',1),(qid,'回答しない','no-answer',2);
insert into questions(survey_version_id,type,title,required,sort_order) values(vid,'single_choice','年代を教えてください。',false,1) returning id into qid;insert into question_options(question_id,label,value,sort_order) values(qid,'10代','10s',0),(qid,'20代','20s',1),(qid,'30代','30s',2),(qid,'40代','40s',3),(qid,'50代','50s',4),(qid,'60代','60s',5),(qid,'70代以上','70plus',6);
insert into questions(survey_version_id,type,title,required,sort_order,settings) values(vid,'rating_10','診療内容はいかがでしたか？',true,2,'{"minLabel":"非常に不満","maxLabel":"非常に満足"}'),(vid,'rating_10','スタッフの対応はいかがでしたか？',true,3,'{"minLabel":"非常に不満","maxLabel":"非常に満足"}');
insert into questions(survey_version_id,type,title,required,sort_order) values(vid,'multiple_choice','当院を選ばれた理由を教えてください。',false,4) returning id into qid;insert into question_options(question_id,label,value,sort_order) values(qid,'自宅・職場から近い','nearby',0),(qid,'家族・知人からの紹介','referral',1),(qid,'Google検索・Googleマップ','google',2),(qid,'ホームページを見て','website',3),(qid,'以前から通院している','returning',4),(qid,'その他','other',5);
insert into questions(survey_version_id,type,title,required,sort_order,settings) values(vid,'textarea','ご意見・ご要望をお聞かせください。',false,5,'{"placeholder":"お気づきの点をご自由にご記入ください。"}');end if;

sid:='20000000-0000-4000-8000-000000000002';vid:='22000000-0000-4000-8000-000000000002';
insert into surveys(id,name,slug,industry,status,current_draft_version_id) values(sid,'三宮胃腸内科','sannomiya-clinic','内科・消化器内科','draft',null) on conflict(id) do update set name=excluded.name;
insert into survey_versions(id,survey_id,version,status,config) values(vid,sid,1,'draft','{"title":"三宮胃腸内科 患者様アンケート","description":"診療品質向上のため、率直なご意見をお聞かせください。","introText":"お忙しいところ恐れ入りますが、アンケートにご協力ください。","anonymousText":"このアンケートは匿名です。個人を特定する情報は取得しません。","completionText":"ご回答ありがとうございました。今後より良い医療サービスづくりに活用させていただきます。","submitLabel":"回答を送信","primaryColor":"#176c80","backgroundColor":"#f1f8fa","logoUrl":null,"iconUrl":null,"googleReviewUrl":null}'::jsonb) on conflict(id) do nothing;update surveys set current_draft_version_id=vid where id=sid;
if not exists(select 1 from questions where survey_version_id=vid) then
insert into questions(survey_version_id,type,title,required,sort_order) values(vid,'single_choice','本日のご来院目的を教えてください。',true,0) returning id into qid;insert into question_options(question_id,label,value,sort_order) values(qid,'検査のみ','exam',0),(qid,'診察（外来）','consultation',1),(qid,'検査＋診察','both',2),(qid,'その他','other',3);
insert into questions(survey_version_id,type,title,required,sort_order,settings) values(vid,'rating_10','診療内容は満足できましたか？',true,1,'{"minLabel":"非常に不満","maxLabel":"非常に満足"}'),(vid,'rating_10','スタッフの対応は満足できましたか？',true,2,'{"minLabel":"非常に不満","maxLabel":"非常に満足"}');
insert into questions(survey_version_id,type,title,required,sort_order) values(vid,'single_choice','当院を選ばれた理由は？',true,3) returning id into qid;insert into question_options(question_id,label,value,sort_order) values(qid,'ホームページ','website',0),(qid,'Googleマップ','google',1),(qid,'クリニック紹介サイト','portal',2),(qid,'看板','sign',3),(qid,'知人紹介','referral',4),(qid,'医療機関からの紹介','medical-referral',5);
insert into questions(survey_version_id,type,title,required,sort_order,settings) values(vid,'textarea','その他、お気づきの点や改善点、ご意見ご要望などございましたらお聞かせください。',false,4,'{"placeholder":"診療やスタッフ対応、院内環境などについてご自由にご記入ください。"}');end if;end $$;
