-- Phase 2: mark Google Sheets webhook results without exposing queue writes.
-- A one-time sync token is generated by the server and stored only in response
-- metadata. The browser never receives it. Queue status can only be updated when
-- response_id and token match.

create or replace function public.mark_google_sheets_sync_result(
  p_response_id uuid,
  p_sync_token text,
  p_status text,
  p_error text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  token_matches boolean := false;
begin
  if p_status not in ('synced', 'failed') then
    raise exception '同期ステータスが不正です';
  end if;

  select exists(
    select 1
    from public.responses
    where id = p_response_id
      and metadata->>'googleSheetsSyncToken' = p_sync_token
  ) into token_matches;

  if not token_matches then
    return false;
  end if;

  update public.google_sheets_sync_queue
  set
    status = p_status,
    attempts = attempts + 1,
    last_attempt_at = now(),
    last_error = case when p_status = 'failed' then left(coalesce(p_error, 'Unknown sync error'), 1000) else null end,
    synced_at = case when p_status = 'synced' then now() else synced_at end
  where response_id = p_response_id;

  return found;
end;
$$;

revoke all on function public.mark_google_sheets_sync_result(uuid,text,text,text) from public;
grant execute on function public.mark_google_sheets_sync_result(uuid,text,text,text) to anon, authenticated;
