create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','sales');
create type public.survey_status as enum ('draft','published','unpublished','archived');
create type public.version_status as enum ('draft','published','superseded');
create type public.question_type as enum ('single_choice','multiple_choice','rating_10','textarea','text');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null default '', email text not null default '', role public.user_role not null default 'sales', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.surveys (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'), industry text not null default '', status public.survey_status not null default 'draft', owner_user_id uuid references public.profiles(id), current_draft_version_id uuid, current_published_version_id uuid, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), published_at timestamptz, archived_at timestamptz);
create table public.survey_versions (id uuid primary key default gen_random_uuid(), survey_id uuid not null references public.surveys(id) on delete cascade, version integer not null check(version>0), status public.version_status not null, config jsonb not null default '{}'::jsonb, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), published_at timestamptz, unique(survey_id,version));
alter table public.surveys add constraint surveys_draft_fk foreign key(current_draft_version_id) references public.survey_versions(id);
alter table public.surveys add constraint surveys_published_fk foreign key(current_published_version_id) references public.survey_versions(id);
create table public.questions (id uuid primary key default gen_random_uuid(), survey_version_id uuid not null references public.survey_versions(id) on delete cascade, type public.question_type not null, title text not null, description text not null default '', required boolean not null default false, sort_order integer not null, settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(survey_version_id,sort_order));
create table public.question_options (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.questions(id) on delete cascade, label text not null, value text not null, sort_order integer not null, unique(question_id,sort_order));
create table public.responses (id uuid primary key default gen_random_uuid(), survey_id uuid not null references public.surveys(id), survey_version_id uuid not null references public.survey_versions(id), submitted_at timestamptz not null default now(), total_score numeric, average_score numeric, metadata jsonb not null default '{}'::jsonb);
create table public.response_answers (id uuid primary key default gen_random_uuid(), response_id uuid not null references public.responses(id) on delete cascade, question_id uuid not null references public.questions(id), value_text text, value_number numeric, value_json jsonb, created_at timestamptz not null default now(), unique(response_id,question_id));
create index surveys_status_idx on public.surveys(status); create index versions_survey_idx on public.survey_versions(survey_id,status); create index questions_version_idx on public.questions(survey_version_id,sort_order); create index responses_survey_idx on public.responses(survey_id,submitted_at desc); create index answers_response_idx on public.response_answers(response_id);

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role in ('admin','sales')) $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin') $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at(); create trigger surveys_touch before update on public.surveys for each row execute function public.touch_updated_at();
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,name,email) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.email,'')); return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.publish_survey(p_survey_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare s surveys; draft survey_versions; new_draft_id uuid; begin if not is_staff() then raise exception '権限がありません'; end if; select * into s from surveys where id=p_survey_id and status<>'archived' for update; select * into draft from survey_versions where id=s.current_draft_version_id and status='draft'; if draft.id is null or not exists(select 1 from questions where survey_version_id=draft.id) then raise exception '公開できる質問がありません'; end if; update survey_versions set status='superseded' where id=s.current_published_version_id; update survey_versions set status='published',published_at=now() where id=draft.id; insert into survey_versions(survey_id,version,status,config,created_by) values(s.id,draft.version+1,'draft',draft.config,auth.uid()) returning id into new_draft_id; insert into questions(id,survey_version_id,type,title,description,required,sort_order,settings) select gen_random_uuid(),new_draft_id,type,title,description,required,sort_order,settings from questions where survey_version_id=draft.id; insert into question_options(question_id,label,value,sort_order) select nq.id,o.label,o.value,o.sort_order from questions oq join questions nq on nq.survey_version_id=new_draft_id and nq.sort_order=oq.sort_order join question_options o on o.question_id=oq.id where oq.survey_version_id=draft.id; update surveys set status='published',current_published_version_id=draft.id,current_draft_version_id=new_draft_id,published_at=now(),updated_by=auth.uid() where id=s.id; return draft.id; end $$;

create or replace function public.submit_survey_response(p_slug text,p_version_id uuid,p_answers jsonb,p_metadata jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare s surveys; r_id uuid; q questions; v jsonb; total numeric:=0; score_count int:=0; begin select * into s from surveys where slug=p_slug and status='published' and current_published_version_id=p_version_id; if s.id is null then raise exception 'このアンケートは公開されていません'; end if; for q in select * from questions where survey_version_id=p_version_id order by sort_order loop v:=p_answers->q.id::text; if q.required and (v is null or v='null'::jsonb or v='""'::jsonb or v='[]'::jsonb) then raise exception '必須項目が未回答です'; end if; if q.type='rating_10' and v is not null then if (v#>>'{}')::numeric not between 1 and 10 then raise exception '評価値が不正です'; end if; total:=total+(v#>>'{}')::numeric; score_count:=score_count+1; end if; end loop; if exists(select 1 from jsonb_object_keys(p_answers) k where not exists(select 1 from questions where survey_version_id=p_version_id and id::text=k)) then raise exception '不明な質問です'; end if; insert into responses(survey_id,survey_version_id,total_score,average_score,metadata) values(s.id,p_version_id,total,case when score_count>0 then round(total/score_count,2) end,coalesce(p_metadata,'{}')) returning id into r_id; for q in select * from questions where survey_version_id=p_version_id loop v:=p_answers->q.id::text; if v is not null then insert into response_answers(response_id,question_id,value_text,value_number,value_json) values(r_id,q.id,case when jsonb_typeof(v)='string' then v#>>'{}' end,case when q.type='rating_10' then (v#>>'{}')::numeric end,case when jsonb_typeof(v) in ('array','object') then v end); end if; end loop; return r_id; end $$;

alter table profiles enable row level security; alter table surveys enable row level security; alter table survey_versions enable row level security; alter table questions enable row level security; alter table question_options enable row level security; alter table responses enable row level security; alter table response_answers enable row level security;
create policy profiles_self on profiles for select to authenticated using(id=auth.uid() or is_admin()); create policy profiles_admin_write on profiles for update to authenticated using(is_admin()) with check(is_admin());
create policy surveys_staff_all on surveys for all to authenticated using(is_staff()) with check(is_staff()); create policy surveys_public_read on surveys for select to anon using(status='published');
create policy versions_staff_all on survey_versions for all to authenticated using(is_staff()) with check(is_staff()); create policy versions_public_read on survey_versions for select to anon using(status='published' and exists(select 1 from surveys s where s.current_published_version_id=survey_versions.id and s.status='published'));
create policy questions_staff_all on questions for all to authenticated using(is_staff()) with check(is_staff()); create policy questions_public_read on questions for select to anon using(exists(select 1 from survey_versions v join surveys s on s.current_published_version_id=v.id where v.id=questions.survey_version_id and v.status='published' and s.status='published'));
create policy options_staff_all on question_options for all to authenticated using(is_staff()) with check(is_staff()); create policy options_public_read on question_options for select to anon using(exists(select 1 from questions q join survey_versions v on v.id=q.survey_version_id join surveys s on s.current_published_version_id=v.id where q.id=question_options.question_id and v.status='published' and s.status='published'));
create policy responses_staff_read on responses for select to authenticated using(is_staff()); create policy answers_staff_read on response_answers for select to authenticated using(is_staff());
revoke all on function public.submit_survey_response(text,uuid,jsonb,jsonb) from public; grant execute on function public.submit_survey_response(text,uuid,jsonb,jsonb) to anon,authenticated; grant execute on function public.publish_survey(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('questionnaire-assets','questionnaire-assets',true,5242880,array['image/png','image/jpeg','image/webp']) on conflict(id) do nothing;
create policy assets_public_read on storage.objects for select using(bucket_id='questionnaire-assets'); create policy assets_staff_insert on storage.objects for insert to authenticated with check(bucket_id='questionnaire-assets' and public.is_staff()); create policy assets_staff_update on storage.objects for update to authenticated using(bucket_id='questionnaire-assets' and public.is_staff()); create policy assets_staff_delete on storage.objects for delete to authenticated using(bucket_id='questionnaire-assets' and public.is_staff());
